version: 23.6.0
docker_files:
  sentry-hh: docker/Dockerfile.sentry
  relay-hh: docker/Dockerfile.relay
  snuba-hh: docker/Dockerfile.snuba
docker_context: .
build_method: nope_build
update_method: python_update
deploy_method: nope_deploy
