version: 24.7.1-2
docker_files:
  getsentry/sentry-hh: docker/Dockerfile.sentry
  getsentry/relay-hh: docker/Dockerfile.relay
  getsentry/snuba-hh: docker/Dockerfile.snuba
  getsentry/vroom-hh: docker/Dockerfile.vroom
  getsentry/symbolicator-hh: docker/Dockerfile.symbolicator
docker_context: .
build_method: nope_build
update_method: python_update
deploy_method: nope_deploy
