---
name: Docker Image CI

'on':
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    permissions:
#      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image-name:
          - sentry
          - relay
          - snuba
          - symbolicator
          - vroom
    steps:
      - name: Build docker images
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: '${{ matrix.image-name }}-hh:${{ github.sha }}'
          file: 'docker/Dockerfile.${{ matrix.image-name }}'

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@915b19bbe73b92a6cf82a1bc12b087c9a19a5fe2
        with:
          image-ref: '${{ matrix.image-name }}-hh:${{ github.sha }}'
          format: sarif
          output: '${{ matrix.image-name }}-trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@aa578102511db1f4524ed59b8cc2bae4f6e88195
        with:
          sarif_file: '${{ matrix.image-name }}-trivy-results.sarif'

      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@f2ba85e044c8f5e5014c9a539328a9c78d3bfa49
        id: scan
        with:
          image: '${{ matrix.image-name }}-hh:${{ github.sha }}'
          fail-build: false
          severity-cutoff: critical

      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif@aa578102511db1f4524ed59b8cc2bae4f6e88195
        with:
          sarif_file: '${{ steps.scan.outputs.sarif }}'
